INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (1, 'scholarships seen by manager', null, 'Manager', '2019/12/11 15:30:20');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (2, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/11 15:31:42');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (3, 'accepted id 8 by supervisor', 8, 'Supervisor', '2019/12/11 15:32:20');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (4, 'scholarships seen by manager', null, 'Manager', '2019/12/11 15:32:30');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (5, 'accepted id 8 by manager', 8, 'Manager', '2019/12/11 15:32:39');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (6, 'scholarships seen by university', null, 'University', '2019/12/11 15:32:41');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (7, 'received id 8 by university', 8, 'University', '2019/12/11 15:33:12');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (8, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/12 15:31:16');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (9, 'scholarships seen by manager', null, 'Manager', '2019/12/12 15:31:42');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (10, 'accepted id 9 by supervisor', 9, 'Supervisor', '2019/12/12 15:32:15');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (11, 'accepted id 9 by manager', 9, 'Manager', '2019/12/12 15:32:41');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (12, 'scholarships seen by university', null, 'University', '2019/12/12 15:33:03');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (13, 'received id 9 by university', 9, 'University', '2019/12/12 15:33:12');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (14, 'scholarships seen by manager', null, 'Manager', '2019/12/13 14:56:52');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (15, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/13 15:29:55');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (16, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/13 15:30:52');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (17, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/13 15:33:22');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (18, 'accepted id 3 by supervisor', 3, 'Supervisor', '2019/12/13 19:04:37');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (19, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/13 19:10:00');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (20, 'accepted id 10 by supervisor', 10, 'Supervisor', '2019/12/13 19:10:09');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (21, 'scholarships seen by manager', null, 'Manager', '2019/12/13 19:17:03');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (22, 'accepted id 10 by manager', 10, 'Manager', '2019/12/13 19:17:20');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (23, 'scholarships seen by supervisor', null, 'Supervisor', '2019/12/13 19:24:31');
INSERT INTO scholarshipmanagement.log (idlog, log, scholarship_id, user_role, date) VALUES (24, 'scholarships seen by manager', null, 'Manager', '2019/12/13 20:06:13');